version: "3"
services:

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.1
    container_name: kibana
    hostname: kibana
    ports:
      - "5601:5601"
    external_links:
      - elasticsearch
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
      - "XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED=false"
      - "XPACK_MONITORING_ENABLED=false"
    depends_on:
      - elasticsearch

  elasticsearch:
    image:  docker.elastic.co/elasticsearch/elasticsearch:7.4.1
    container_name: elasticsearch
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
    volumes:
      - ./volumes/elasticsearch:/opt/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:7.4.1
    container_name: logstash
    hostname: logstash
    volumes:
      - ./Section_04/config/logstash.yml:/usr/share/logstash/pipeline/logstash.conf
      - ./Section_04/downloads/access_log:/usr/share/logstash/logs/access_log
    depends_on:
      - elasticsearch

  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: daniel1

  adminer:
    image: adminer
    container_name: adminer
    hostname: adminer
    restart: always
    ports:
      - 8080:8080
