version: "3"
services:

  elasticsearch:
    image:  docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
    volumes:
      - ./volumes/elasticsearch:/opt/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    container_name: kibana
    hostname: kibana
    ports:
      - "5601:5601"
    external_links:
      - elasticsearch
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
      - "XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED=false"
      - "XPACK_MONITORING_ENABLED=false"
    depends_on:
      - elasticsearch
